services:
  env: docker  - type: web
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080   # Render overrides this automatically
      - key: TRELLO_KEY
        sync: false
      - key: TRELLO_TOKEN
        sync: false
      - key: TRELLO_LIST_ID
        sync: false
      - key: XERO_CLIENT_ID
        sync: false
    name: easyread-quoter
